name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21.4
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -short ./...
      env:
        GOOS: linux
        GOARCH: 386
        
    # - name: Build
    #   run: make geth

    # - name: Test
    #   run: go test ./core/... ./miner ./eth/... ./rpc ./internal/ethapi/... ./les/...

    # - name: Lint
    #   run: make lint
